# http://docs.travis-ci.com/user/build-configuration/

language: php

os: linux

dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

install:
  - ant
  - composer self-update
  - composer require --dev phpunit/phpunit ^6.0 php-coveralls/php-coveralls ^2.1
  - composer install --dev

before_script:
  - mysql --user=root -e "CREATE USER 'foo'@'localhost' IDENTIFIED BY 'foo';"
  - mysql --user=root -e "GRANT ALL PRIVILEGES ON *.* TO 'foo'@'localhost'"
  - mysql -e 'create database IF NOT EXISTS boxbilling'
  - mysql -D boxbilling < src/install/structure.sql
  - mysql -D boxbilling < src/install/content.sql
  - mv ./src/bb-config-sample.php ./src/bb-config.php

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false

before_deploy:
  - npm install -g grunt-cli
  - npm install
  - grunt
  - ant release

deploy:
  provider: releases
  api-key:
    secure: tVzZ+3U0ndBGvoUpFqA6ikg6fDKnPgMoNqK1pvTdEp0xmrFtjMP/fuc8+awObhj89iEC+MyzfsOP57CZbHR/UjmUSHPQew+BvTwxYmTUzgUeyUrYsTEI7WJgB7tsL35aRgrpxk102tlSmlX7EonufUT0svPOAQ1p4NgZRm3GI3A=
  file: ./build/distribution/BoxBilling.zip
  on:
    tags: true
    all_branches: true
    php: 7.4
